name: Test Coverage

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      
      - name: Install dependencies
        run: sudo apt-get install -y libharfbuzz-dev libfribidi-dev libcurl4-openssl-dev libxml2-dev libssl-dev cmake libnlopt-dev

      - name: Run tests and report coverage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          Rscript -e 'install.packages("devtools")'
          Rscript -e 'install.packages("covr")'
          Rscript -e 'devtools::install()'
          Rscript -e 'covr::coveralls()'
