on: [push, pull_request]

name: deploy-shiny

jobs:
  deploy-shiny:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install shiny and deploy
        run: |
          Rscript -e "install.packages(c('shiny', 'rsconnect'), type = 'binary'); rsconnect::setAccountInfo(name='calorimetry', token=${{secrets.SHINYAPPS_TOKEN}}, secret=${{secrets.SHINYAPPS_SECRET}}); rsconnect::deployApp(appName = 'calorimetry')"
