on: [push, pull_request]

name: make-badges

jobs:
  make-badges:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create badges
        run: |
          sudo apt-get install -y npm
          npm install -g badge-maker
          badge build passed :green > mybadge.svg
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Badges
          path: mybadge.svg

      - name: Update README
        run: |
          echo -n "-    [status](https://github.com/stephanmg/calorimetry/blob/data/mybadge.svg)" >> README.md

      - name: Commit
        run: |
          git checkout data
          git add mybadge.svg
          git config --global user.name 'CI'
          git commit -am "Updating README"
          git push
