on: [push, pull_request]

name: test-shiny

jobs:
  test-shiny:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get install -y libharfbuzz-dev libfribidi-dev libcurl4-openssl-dev libxml2-dev libssl-dev cmake libnlopt-dev
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.2'
      - name: Install R dependencies
        run: Rscript -e "install.packages(c('tidyverse', 'testthat', 'here'))"
      - name: Run tests
        run: Rscript -e "source('tests/testthat.R')"
