name: tests

jobs:
  test-shiny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.2'
      - name: Install dependencies
        run: Rscript -e "install.packages(c('testthat', 'tidyverse', 'here'))"
      - name: Run tests
        run: Rscript -e "source('tests/testthat.R')"
